# Generated by Django 4.0.7 on 2022-12-04 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aec_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post_reaction',
            name='type',
            field=models.CharField(choices=[('LIKE', 'LIKE'), ('DISLIKE', 'DISLIKE')], max_length=100, null=True),
        ),
    ]
