# Generated by Django 4.0.7 on 2022-12-06 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aec_app', '0003_post_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='post_reaction',
            name='reacted_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='post_comment',
            name='updated_at',
            field=models.DateTimeField(null=True),
        ),
    ]
