# Generated by Django 4.1.3 on 2022-12-15 09:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('aec_app', '0004_post_reaction_reacted_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client_Requests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('SHARED', 'SHARED'), ('REJECTED', 'REJECTED'), ('COMPLETED', 'COMPLETED')], default='PENDING', max_length=100, null=True)),
                ('role', models.CharField(max_length=50, null=True)),
                ('location', models.CharField(max_length=50, null=True)),
                ('requirementdetails', models.CharField(max_length=500, null=True)),
                ('experience', models.IntegerField(default=0)),
                ('related', models.CharField(max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_acceptedbyUser', models.BooleanField(default=False)),
                ('request_from', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='request_from', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
