# Generated by Django 4.1.3 on 2022-12-15 11:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('aec_app', '0005_client_requests'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proposals_Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('SHARED', 'SHARED'), ('REJECTED', 'REJECTED'), ('COMPLETED', 'COMPLETED')], default='PENDING', max_length=100, null=True)),
                ('eligible', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eligible', to=settings.AUTH_USER_MODEL)),
                ('proposal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proposal', to='aec_app.client_requests')),
                ('proposal_from', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
