# Generated by Django 4.1.3 on 2022-12-15 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aec_app', '0006_proposals_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposals_admin',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('ACCEPTED', 'ACCEPTED'), ('PROPOSAL_SENT', 'PROPOSAL_SENT'), ('REJECTED_USER', 'REJECTED_USER'), ('ACCEPTED_USER', 'ACCEPTED_USER'), ('COMPLETED', 'COMPLETED')], default='PENDING', max_length=100, null=True),
        ),
    ]
