# Generated by Django 4.1.3 on 2022-12-16 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aec_app', '0007_alter_proposals_admin_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposals_admin',
            name='is_accepted',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='proposals_admin',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('ACCEPTED', 'ACCEPTED'), ('PROPOSAL_SENT', 'PROPOSAL_SENT'), ('COMPLETED', 'COMPLETED')], default='PENDING', max_length=100, null=True),
        ),
    ]
