# Generated by Django 4.1.3 on 2022-12-19 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aec_app', '0008_proposals_admin_is_accepted_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aec_Proposals_User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposal_content', models.FileField(null=True, upload_to='proposalcontent')),
                ('rate', models.IntegerField(default=0)),
                ('send_at', models.DateTimeField(auto_now_add=True)),
                ('is_accepted', models.BooleanField(default=False)),
                ('admin_proposal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proposal_admin', to='aec_app.proposals_admin')),
            ],
        ),
    ]
