# Generated by Django 4.1.3 on 2022-12-21 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aec_app', '0010_aec_proposals_user_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposals_admin',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('ACCEPTED', 'ACCEPTED'), ('PROPOSAL_SENT', 'PROPOSAL_SENT'), ('REJECTED', 'REJECTED'), ('COMPLETED', 'COMPLETED')], default='PENDING', max_length=100, null=True),
        ),
    ]
