# Generated by Django 4.1.3 on 2022-12-22 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aec_app', '0011_alter_proposals_admin_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aec_proposals_user',
            name='admin_proposal',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='proposal_admin', to='aec_app.proposals_admin'),
            preserve_default=False,
        ),
    ]
