# Generated by Django 4.1.3 on 2022-11-25 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileverification',
            name='cerificate',
            field=models.FileField(upload_to='certificates'),
        ),
        migrations.AlterField(
            model_name='profileverification',
            name='cv',
            field=models.FileField(upload_to='cv'),
        ),
        migrations.AlterField(
            model_name='profileverification',
            name='id_proof',
            field=models.FileField(upload_to='idproofs'),
        ),
    ]
