# Generated by Django 4.1.3 on 2022-11-26 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_alter_profileverification_cerificate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileverification',
            name='paid_at',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='phone_number',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
