# Generated by Django 4.1.3 on 2022-11-26 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0003_profileverification_paid_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='full_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
