# Generated by Django 4.0.7 on 2022-11-28 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0004_alter_account_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='cover_pic',
            field=models.FileField(blank=True, null=True, upload_to='cover_pic'),
        ),
        migrations.AddField(
            model_name='account',
            name='pro_pic',
            field=models.FileField(blank=True, null=True, upload_to='pro_pic'),
        ),
    ]
