# Generated by Django 4.0.7 on 2022-11-28 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0005_account_cover_pic_account_pro_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='pro_pic',
            field=models.FileField(blank=True, default='/1.png', null=True, upload_to='pro_pic'),
        ),
    ]
