# Generated by Django 4.0.7 on 2022-11-28 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0006_alter_account_pro_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='cover_pic',
            field=models.FileField(blank=True, default='/cover.jpg', null=True, upload_to='cover_pic'),
        ),
    ]
