# Generated by Django 4.0.7 on 2022-11-28 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0007_alter_account_cover_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileverification',
            name='verif_send_status',
            field=models.BooleanField(default=False),
        ),
    ]
