# Generated by Django 4.0.7 on 2022-11-28 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0008_profileverification_verif_send_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileverification',
            name='is_rejected',
            field=models.BooleanField(default=False),
        ),
    ]
