# Generated by Django 4.0.7 on 2022-11-28 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0009_profileverification_is_rejected'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileverification',
            name='date_of_birth',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='profileverification',
            name='description',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='profileverification',
            name='portfolio_website',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
