# Generated by Django 4.0.7 on 2022-11-28 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0011_profileverification_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profileverification',
            name='cerificate',
        ),
        migrations.AddField(
            model_name='profileverification',
            name='certificate',
            field=models.FileField(null=True, upload_to='certificates'),
        ),
        migrations.AlterField(
            model_name='profileverification',
            name='cv',
            field=models.FileField(null=True, upload_to='cv'),
        ),
        migrations.AlterField(
            model_name='profileverification',
            name='id_proof',
            field=models.FileField(null=True, upload_to='idproofs'),
        ),
    ]
