# Generated by Django 4.1.3 on 2022-11-30 05:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0012_remove_profileverification_cerificate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileverification',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
