# Generated by Django 4.1.3 on 2022-12-01 15:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0013_alter_profileverification_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='date_joined',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_title', models.CharField(max_length=100, null=True)),
                ('project_desc', models.CharField(max_length=200, null=True)),
                ('project_image', models.FileField(null=True, upload_to='projects')),
                ('project_status', models.CharField(choices=[('COMPLETED', 'COMPLETED'), ('PENDING', 'PENDING')], default='PENDING', max_length=100, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_project', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Network',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_follow', models.BooleanField(default=False, null=True)),
                ('is_connect', models.BooleanField(default=False, null=True)),
                ('followed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='followed_by', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_network', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
