# Generated by Django 4.0.7 on 2022-12-05 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0015_projects_project_client_review_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='network',
            name='connect_status',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
