# Generated by Django 4.0.7 on 2022-12-05 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0016_network_connect_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='network',
            old_name='user',
            new_name='followed_to',
        ),
    ]
