# Generated by Django 4.0.7 on 2022-12-06 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0017_rename_user_network_followed_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='network',
            name='followed_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='network',
            name='is_rejected',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='network',
            name='is_connect',
            field=models.BooleanField(null=True),
        ),
    ]
