# Generated by Django 4.1.3 on 2022-12-22 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0022_account_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='projects',
            field=models.IntegerField(default=0),
        ),
    ]
