# Generated by Django 4.1.3 on 2022-12-23 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0024_projects_posted_on_projects_reviewed_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='project_status',
            field=models.CharField(choices=[('COMPLETED', 'COMPLETED')], default='PENDING', max_length=100, null=True),
        ),
    ]
