# Generated by Django 4.1.3 on 2023-01-09 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aec_app', '0013_client_requests_is_rejected'),
        ('user_app', '0029_alter_account_otp'),
        ('chat_app', '0004_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='network',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notify_network', to='user_app.network'),
        ),
        migrations.AddField(
            model_name='notifications',
            name='notification_of',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='notifications',
            name='post_notification',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notify_post', to='aec_app.post'),
        ),
    ]
