# Generated by Django 4.1.3 on 2023-01-09 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0005_notifications_network_notifications_notification_of_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notifications',
            old_name='network',
            new_name='network_notification',
        ),
    ]
