export const ALL_USERS_LIST_REQUEST = 'ALL_USERS_LIST_REQUEST'
export const ALL_USERS_LIST_SUCCESS = 'ALL_USERS_LIST_SUCCESS'
export const ALL_USERS_LIST_FAIL = 'ALL_USERS_LIST_FAIL'

export const USER_STATUS_CHANGE = 'USER_STATUS_CHANGE'

export const ALL_PROFILEVERIFICATIONS_LIST_REQUEST = 'ALL_PROFILEVERIFICATIONS_LIST_REQUEST'
export const ALL_PROFILEVERIFICATIONS_LIST_SUCCESS = 'ALL_PROFILEVERIFICATIONS_LIST_SUCCESS'
export const ALL_PROFILEVERIFICATIONS_LIST_FAIL = 'ALL_PROFILEVERIFICATIONS_LIST_FAIL'

export const USER_PROFILEVERIFIED_SUCCESS = 'USER_PROFILEVERIFIED_SUCCESS'
export const USER_PROFILEREJECTED_SUCCESS = 'USER_PROFILEREJECTED_SUCCESS'

export const ALL_POSTS_LIST_REQUEST = 'ALL_POSTS_LIST_REQUEST'
export const ALL_POSTS_LIST_SUCCESS = 'ALL_POSTS_LIST_SUCCESS'
export const ALL_POSTS_LIST_FAIL = 'ALL_POSTS_LIST_FAIL'





