export const ADMIN_PROPOSALS_LIST='ADMIN_PROPOSALS_LIST'
export const ADMIN_PROPOSALS_LIST_FAIL='ADMIN_PROPOSALS_LIST_FAIL'

export const ADMIN_PROPOSALS_ACCEPTED_LIST='ADMIN_PROPOSALS_ACCEPTED_LIST'
export const ADMIN_PROPOSALS_ACCEPTED_LIST_FAIL='ADMIN_PROPOSALS_ACCEPTED_LIST'

export const ADMIN_PROPOSALS_ONPROCESS_LIST='ADMIN_PROPOSALS_ONPROCESS_LIST'
export const ADMIN_PROPOSALS_ONPROCESS_LIST_FAIL='ADMIN_PROPOSALS_ONPROCESS_LIST_FAIL'

export const ADMIN_PROPOSALS_REJECTED_LIST='ADMIN_PROPOSALS_REJECTED_LIST'
export const ADMIN_PROPOSALS_REJECTED_LIST_FAIL='ADMIN_PROPOSALS_REJECTED_LIST_FAIL'


export const ADMIN_PROPOSAL_ACCEPT='ADMIN_PROPOSAL_ACCEPT'
export const ADMIN_PROPOSAL_REJECT='ADMIN_PROPOSAL_REJECT'

export const SEND_PROPOSAL_TO_USER='SEND_PROPOSAL_TO_USER'
export const COMPLETED_PROPOSAL_WORK='COMPLETED_PROPOSAL_WORK'

export const PROPOSAL_INTERACTION_RESET='PROPOSAL_INTERACTION_RESET'

   // ADMIN_PROPOSALS,
    // ADMIN_PROPOSALS_ACCEPTED,
    // ADMIN_PROPOSALS_ONPROCESS,
    // ADMIN_PROPOSALS_REJECTED,