export const USER_LOGIN_REQUEST='USER_LOGIN_REQUEST'
export const USER_LOGIN_SUCCESS='USER_LOGIN_SUCCESS'
export const USER_LOGIN_FAIL='USER_LOGIN_FAIL'

export const USER_LOGOUT = 'USER_LOGOUT'


export const USER_REGISTER_REQUEST='USER_REGISTER_REQUEST'
export const USER_REGISTER_SUCCESS='USER_REGISTER_SCCESS'
export const USER_REGISTER_FAIL='USER_REGISTER_FAIL'


export const USER_PROFILEVERIFY_REQUEST='USER_PROFILEVERIFY_REQUEST'
export const USER_PROFILEVERIFY_SUCCESS='USER_PROFILEVERIFY_SCCESS'
export const USER_PROFILEVERIFY_FAIL='USER_PROFILEVERIFY_FAIL'


export const USER_PROFILE_REQUEST = 'USER_PROFILE_REQUEST'
export const USER_PROFILE_SUCCESS = 'USER_PROFILE_SUCCESS'
export const USER_PROFILE_FAIL = 'USER_PROFILE_FAIL'
export const USER_PROFILE_RESET = 'USER_PROFILE_RESET'

export const OTHER_USER_PROFILE_REQUEST = 'OTHER_USER_PROFILE_REQUEST'
export const OTHER_USER_PROFILE_SUCCESS = 'OTHER_USER_PROFILE_SUCCESS'
export const OTHER_USER_PROFILE_FAIL = 'OTHER_USER_PROFILE_FAIL'
export const OTHER_USER_PROFILE_RESET = 'OTHER_USER_PROFILE_RESET'

export const USER_UPDATE_PROFILE_REQUEST = 'USER_UPDATE_PROFILE_REQUEST'
export const USER_UPDATE_PROFILE_SUCCESS = 'USER_UPDATE_PROFILE_SUCCESS'
export const USER_UPDATE_PROFILE_FAIL = 'USER_UPDATE_PROFILE_FAIL'
export const USER_UPDATE_PROFILE_RESET = 'USER_UPDATE_PROFILE_RESET'

export const USER_PROFILEREQUEST_INDIVIDUAL_VIEW = 'USER_PROFILEREQUEST_INDIVIDUAL_VIEW'
export const USER_PROFILEREQUEST_INDIVIDUAL_FAILED = 'USER_PROFILEREQUEST_INDIVIDUAL_FAILED'
export const DELETE_PROFILE_REQUEST='DELETE_PROFILE_REQUEST'

export const USER_ADD_POST_REQUEST = 'USER_ADD_POST_REQUEST'
export const USER_ADD_POST_SUCCESS = 'USER_ADD_POST_SUCCESS'
export const USER_ADD_POST_FAIL = 'USER_ADD_POST_FAIL'
export const USER_ADD_POST_RESET = 'USER_ADD_POST_RESET'

export const USER_FEED_ALL_POSTS_LIST_REQUEST='USER_FEED_ALL_POSTS_LIST_REQUEST'
export const USER_FEED_ALL_POSTS_LIST_SUCCESS='USER_FEED_ALL_POSTS_LIST_SUCCESS'
export const USER_FEED_ALL_POSTS_LIST_FAIL='USER_FEED_ALL_POSTS_LIST_FAIL'

export const USER_ALL_SUGGESTIONS='USER_ALL_SUGGESTIONS'

export const USER_LIKED_POST='USER_LIKED_POST'
export const USER_DISLIKED_POST='USER_DISLIKED_POST'
export const USER_COMMENTED='USER_COMMENTED'
export const USER_COMMENT_REPLY='USER_COMMENT_REPLY'
export const USER_INTERACTION_RESET='USER_INTERACTION_RESET'

export const UNFOLLOW_FOLLOW_USER='UNFOLLOW_FOLLOW_USER'
export const SEND_CONNECTION_REQUEST='SEND_CONNECTION_REQUEST'
export const REJECT_CONNECTION_REQUEST='REJECT_CONNECTION_REQUEST'
export const USER_NETWORK_RESET='USER_NETWORK_RESET'

export const TO_PREMIUM_REQUEST='TO_PREMIUM_REQUEST'
export const TO_PREMIUM_SUCCESS='TO_PREMIUM_SUCCESS'
export const TO_PREMIUM_FAILED='TO_PREMIUM_FAILED'
export const TO_PREMIUM_RESET='TO_PREMIUM_RESET'

export const USER_CONNECT_US_REQUEST='USER_CONNECT_US_REQUEST'
export const USER_CONNECT_US_SUCCESS='USER_CONNECT_US_SUCCESS'
export const USER_CONNECT_US_FAIL='USER_CONNECT_US_FAIL'

export const USER_CONNECT_US_RESET='USER_CONNECT_US_RESET'







export const USER_CONNECT_LIST_ALL_REQUEST='USER_CONNECT_LIST_ALL_REQUEST'
export const USER_CONNECT_LIST_ALL_SUCCESS='USER_CONNECT_LIST_ALL_SUCCESS'
export const USER_CONNECT_LIST_ALL_FAIL='USER_CONNECT_LIST_ALL_FAIL'

export const USER_CONNECT_LIST_ALL_RESET='USER_CONNECT_LIST_ALL_RESET'


export const USER_PROPOSAL_BIDS_ALL_REQUEST='USER_PROPOSAL_BIDS_ALL_REQUEST'
export const USER_PROPOSAL_BIDS_ALL_SUCCESS='USER_PROPOSAL_BIDS_ALL_SUCCESS'
export const USER_PROPOSAL_BIDS_ALL_FAIL='USER_PROPOSAL_BIDS_ALL_FAIL'


