export const USER_LOGIN_REQUEST='USER_LOGIN_REQUEST'
export const USER_LOGIN_SUCCESS='USER_LOGIN_SUCCESS'
export const USER_LOGIN_FAIL='USER_LOGIN_FAIL'

export const USER_LOGOUT = 'USER_LOGOUT'


export const USER_REGISTER_REQUEST='USER_REGISTER_REQUEST'
export const USER_REGISTER_SUCCESS='USER_REGISTER_SCCESS'
export const USER_REGISTER_FAIL='USER_REGISTER_FAIL'


export const USER_PROFILEVERIFY_REQUEST='USER_PROFILEVERIFY_REQUEST'
export const USER_PROFILEVERIFY_SUCCESS='USER_PROFILEVERIFY_SCCESS'
export const USER_PROFILEVERIFY_FAIL='USER_PROFILEVERIFY_FAIL'

// export const USER_PROFILEVERIFIED_SUCCESS='USER_PROFILEVERIFIED_SUCCESS'
// export const USER_PROFILEVERIFIED_FAIL='USER_PROFILEVERIFIED_FAIL'

export const USER_PROFILE_REQUEST = 'USER_PROFILE_REQUEST'
export const USER_PROFILE_SUCCESS = 'USER_PROFILE_SUCCESS'
export const USER_PROFILE_FAIL = 'USER_PROFILE_FAIL'
export const USER_PROFILE_RESET = 'USER_PROFILE_RESET'

export const USER_UPDATE_PROFILE_REQUEST = 'USER_UPDATE_PROFILE_REQUEST'
export const USER_UPDATE_PROFILE_SUCCESS = 'USER_UPDATE_PROFILE_SUCCESS'
export const USER_UPDATE_PROFILE_FAIL = 'USER_UPDATE_PROFILE_FAIL'
export const USER_UPDATE_PROFILE_RESET = 'USER_UPDATE_PROFILE_RESET'

